version: '3'
services:
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./nginx/
            dockerfile: Dockerfile
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html/api-easy-payment
        ports:
            - "80:80"            
        links:
            - php-fpm
        networks:
            - payment

    redis:
        container_name: redis        
        build:
            context: ./redis/
            dockerfile: Dockerfile   
        ports:
             - "6379:6379"
        networks:
            - payment


    pgadmin:
        image: dpage/pgadmin4
        restart: always
        container_name: pgadmin
        environment:
             - PGADMIN_DEFAULT_EMAIL=user@domain.com
             - PGADMIN_DEFAULT_PASSWORD=SuperSecret
             - PGADMIN_LISTEN_PORT=5050
        ports:
            - "5050:5050"
        networks:
            - payment  
       

    php-fpm:
        container_name: php-fpm
        restart: always
        build:
            context: ./php-fpm            
            dockerfile: Dockerfile
        expose:
            - "9000"    
        volumes:
            - .:/var/www/html/api-easy-payment
        networks:
            - payment

    postgres:
        container_name: postgresql
        build:
            context: ./postgresql
            dockerfile: Dockerfile
        ports:
            - "5431:5432"
#        volumes:
#            - ${POSTGRES_DATA}:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=payment_dev
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
        networks:
            - payment

networks:
    payment:
        driver: bridge

